"""autogenerated by genpy from segbot_nlp/VoiceCommand.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class VoiceCommand(genpy.Message):
  _md5sum = "3f928abb425ceda8389063403b3f9534"
  _type = "segbot_nlp/VoiceCommand"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 commandCode
float32 distance
float32 angle
int32 location
int32 numTimes
string commandText

"""
  __slots__ = ['commandCode','distance','angle','location','numTimes','commandText']
  _slot_types = ['int32','float32','float32','int32','int32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       commandCode,distance,angle,location,numTimes,commandText

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VoiceCommand, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.commandCode is None:
        self.commandCode = 0
      if self.distance is None:
        self.distance = 0.
      if self.angle is None:
        self.angle = 0.
      if self.location is None:
        self.location = 0
      if self.numTimes is None:
        self.numTimes = 0
      if self.commandText is None:
        self.commandText = ''
    else:
      self.commandCode = 0
      self.distance = 0.
      self.angle = 0.
      self.location = 0
      self.numTimes = 0
      self.commandText = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_i2f2i.pack(_x.commandCode, _x.distance, _x.angle, _x.location, _x.numTimes))
      _x = self.commandText
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.commandCode, _x.distance, _x.angle, _x.location, _x.numTimes,) = _struct_i2f2i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.commandText = str[start:end].decode('utf-8')
      else:
        self.commandText = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_i2f2i.pack(_x.commandCode, _x.distance, _x.angle, _x.location, _x.numTimes))
      _x = self.commandText
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.commandCode, _x.distance, _x.angle, _x.location, _x.numTimes,) = _struct_i2f2i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.commandText = str[start:end].decode('utf-8')
      else:
        self.commandText = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_i2f2i = struct.Struct("<i2f2i")
